--- # playbook with conditions
- hosts: fedora:ubuntu
  user: ansible
  become: yes
  connection: ssh
  tasks: 
    - name: install apache2 
      command: apt-get install apache2 -y
      when: ansible_os_family=="Debian"
    - name: install apache for RedHat
      command: yum install httpd -y
      when: ansible_os_family=="RedHat"
...
