--- # playbook with handlers
- hosts: fedora
  user: ansible
  become: yes
  connection: ssh
  vars: 
    pkgname: httpd
  tasks: 
    - name: install package in the fedora linux
      action: yum name='{{pkgname}}' state=present
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service name='{{pkgname}}' state=restarted
...

